### ISSUE TITLE
Warp network point does not get place on Ginger Island

### ISSUE THREAD

**Issue by KMFrench1** [tlitookilakin/WarpNetwork#1]
https://smapi.io/log/d58cd05d90bb43e1abc149dc7729f7eb

I get the follow error in the log.
[Warp Network] No tile in building layer, could not add access point: 'island' @ 0, 0

And when I go the ginger island and click the statue the warp network does not open.

I also put this in bug tracker on nexus, I was not sure where to put it.

**Comment by tlitookilakin** [comment]
resolved on nexus
