### ISSUE TITLE
Warp totems and the deconstructor

### ISSUE THREAD

**Issue by NormanPCN** [tlitookilakin/WarpNetwork#5]
With this mod, 1.2.2 tested, one cannot place a consumable warp totem into a deconstructor. You are always warped, or the do you want to warp dialog is displayed.

I don't do this much, if at all. I got an island warp totem as loot in the volcano. I have the island obelisk, so I tried to put the totem into a deconstructor to get a dragon tooth. Then sell the tooth.

**Comment by tlitookilakin** [comment]
This should be fixed in the 1.2.3 alpha. Can you try it and let me know?

**Comment by NormanPCN** [comment]
Alpha-1 does allow me to place a warm totem in a deconstructor.

I'll just also confirm that the warp menu does work in Alpha-1 without the need to do a GMCM option save (when after obelisk is config setting. always, always worked).
